# Railway.toml - Configuration for Railway deployment

[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.railway"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Environment variables
[env]
NODE_ENV = "production"
PORT = "8080"
AI_API_PORT = "3006"
BLOCKCHAIN_API_PORT = "3007"
ADMIN_API_PORT = "3008"

# Health check
[healthcheck]
command = ["curl", "-f", "http://localhost:8080/health"]
interval = 30
timeout = 10
retries = 3
startPeriod = 40

# Services configuration
[[services]]
name = "weather-nft-frontend"
source = "."
build.dockerfile = "Dockerfile.railway"

[[services]]
name = "weather-nft-ai"
source = "."
build.dockerfile = "Dockerfile.ai.railway"
env.PORT = "3006"

[[services]]
name = "weather-nft-blockchain"
source = "."
build.dockerfile = "Dockerfile.blockchain.railway"
env.PORT = "3007"

[[services]]
name = "weather-nft-admin"
source = "."
build.dockerfile = "Dockerfile.admin.railway"
env.PORT = "3008"